name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build shared iOS framework
        run: ./gradlew :composeApp:assembleXCFramework --stacktrace

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Build iOS App
        run: |
          xcodebuild \
            -scheme iosApp \
            -workspace iosApp/iosApp.xcworkspace \
            -sdk iphoneos \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Create IPA
        run: |
          mkdir -p Payload
          cp -r iosApp/build/Debug-iphoneos/*.app Payload/
          zip -r iosApp.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: iosApp-ipa
          path: iosApp.ipa
